# NumPy

In [1]:
# NumPy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
# Creating Arrays

In [5]:
sample_array = np.array([1, 2, 3, 4])

In [6]:
sample_array

array([1, 2, 3, 4])

In [17]:
sample_arraye = np.array([10, 20, 30, 40])

In [19]:
sample_arraye

array([10, 20, 30, 40])

In [15]:
# 3D Array(a Matrix) with 2 rows and 2 columns

In [20]:
sample_array_2 = np.array([[1,2],[3,4]])

In [21]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [22]:
sample_array_example = np.array([[10,20],[30,40]])

In [23]:
sample_array_example

array([[10, 20],
       [30, 40]])

In [24]:
# 3D Tensor (2 matrices, each with 2 rows and 2 columns)

In [30]:
sample_tensor_3 =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [31]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
sample_tensor_2 = np.array([[[10, 20,],[30, 40]], [[50, 60],[70, 80]]])

In [38]:
sample_tensor_2 

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [36]:
# Dimension

In [39]:
# if array is 0- Dimension then call that array as (Scalar) 5
# if array is 1- Dimension then call that array as (Vector) for ex = [1,2,3,4]
# if array is 2- Dimension then call that array as (Matrix) in it is (rows, columns)
# if array is 3- Dimension then call that array as (Tensor) in it is (page, rows, columns)

In [40]:
# Properties of Array 

In [44]:
sample_array= np.array([[1,2,3],[4,5,6]])

In [45]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# check the Shape of array

In [49]:
sample_array.shape

(2, 3)

In [50]:
# Dimensions

In [51]:
sample_array.ndim

2

In [52]:
# total elements 

In [57]:
sample_array.size 

6

In [54]:
# data type

In [56]:
sample_array.dtype

dtype('int64')

In [58]:
sample_tensor_4 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [59]:
sample_tensor_4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
sample_tensor_4.shape


(2, 2, 3)

In [61]:
sample_tensor_4.ndim

3

In [62]:
sample_tensor_4.size


12

In [63]:
sample_tensor_4.dtype

dtype('int64')

In [64]:
# Special Arrays

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
np.arange(0,10,2)   # (start, stop, step)

array([0, 2, 4, 6, 8])

In [72]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [73]:
np.arange(0,150,8)

array([  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96,
       104, 112, 120, 128, 136, 144])

In [75]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [76]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [78]:
# Indexing and Slicing

In [79]:
sample_array = np.array([10, 20, 30, 40])

In [80]:
sample_array

array([10, 20, 30, 40])

In [81]:
sample_array[0]

np.int64(10)

In [82]:
sample_array[1]

np.int64(20)

In [83]:
sample_array[2]

np.int64(30)

In [84]:
sample_array[-1]

np.int64(40)

In [85]:
# Slicing 

In [86]:
sample_array[1:3]

array([20, 30])

In [87]:
# Array Operations

In [89]:
a = np.array([1,2,3])

In [90]:
b = np.array([4,5,6])

In [91]:
a

array([1, 2, 3])

In [92]:
b

array([4, 5, 6])

In [95]:
a + b

array([5, 7, 9])

In [96]:
a - b

array([-3, -3, -3])

In [97]:
a * b

array([ 4, 10, 18])

In [98]:
a / b

array([0.25, 0.4 , 0.5 ])

In [99]:
a % b

array([1, 2, 3])

In [100]:
c = np.array([10,20,30])

In [101]:
d = np.array([40,50,60])

In [102]:
c

array([10, 20, 30])

In [103]:
d

array([40, 50, 60])

In [104]:
c + d

array([50, 70, 90])

In [105]:
c - d

array([-30, -30, -30])

In [106]:
c * d

array([ 400, 1000, 1800])

In [107]:
c / d

array([0.25, 0.4 , 0.5 ])

In [108]:
c % d

array([10, 20, 30])

In [109]:
# Mathematical Functions

In [112]:
sample_array = np.array([1,4,9])

In [113]:
sample_array

array([1, 4, 9])

In [116]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [118]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [119]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [121]:
sample_array = np.array([10,20,30])

In [122]:
np.log(sample_array)

array([2.30258509, 2.99573227, 3.40119738])

In [123]:
# Statistical Functions

In [124]:
sample_array = np.array([1,2,3,4,5])

In [125]:
sample_array

array([1, 2, 3, 4, 5])

In [127]:
np.mean(sample_array)

np.float64(3.0)

In [129]:
np.median(sample_array)

np.float64(3.0)

In [133]:
np.std(sample_array)   # standard Deviation

np.float64(1.4142135623730951)

In [134]:
np.min(sample_array)

np.int64(1)

In [135]:
np.max(sample_array)

np.int64(5)

In [136]:
# Reshapimg Arrays

In [142]:
sample_array = np.arange(0,6,1)  # np.arange(6)

In [143]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [145]:
reshaped = sample_array.reshape(2,3)

In [146]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
# Flattaning

In [153]:
sample_array = np.array([[1,2],[3,4]])

In [154]:
sample_array

array([[1, 2],
       [3, 4]])

In [156]:
sample_array.flatten()

array([1, 2, 3, 4])

In [163]:
sample_tensor= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [164]:
sample_tensor.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
# Joining Arrays

In [166]:
a = np.array([1,2])

In [167]:
b = np.array([3,4])

In [168]:
a


array([1, 2])

In [169]:
b

array([3, 4])

In [170]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [171]:
np.concat((a,b))

array([1, 2, 3, 4])

In [172]:
# Spliting Arrays

In [173]:
sample_array = np.array([1,2,3,4])

In [174]:
sample_array

array([1, 2, 3, 4])

In [175]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [176]:
# Random Module

In [177]:
np.random.rand(3)

array([0.03436816, 0.39990389, 0.39552387])

In [178]:
np.random.randint(1,10,5)

array([7, 1, 5, 9, 6], dtype=int32)

In [179]:
# Axis Concept

In [180]:
sample_array = np.array([[1,2],[3,4]])

In [181]:
sample_array

array([[1, 2],
       [3, 4]])

In [183]:
sample_array.shape  # rows and colunms

(2, 2)

In [184]:
np.sum(sample_array,axis = 0)

array([4, 6])

In [185]:
np.sum(sample_array,axis = 1)

array([3, 7])

In [186]:
# NaN & Missing Values

In [187]:
sample_array = np.array([1,np.nan,3])

In [188]:
sample_array

array([ 1., nan,  3.])

In [190]:
np.isnan(sample_array)

array([False,  True, False])

In [192]:
# create two numpy arrays and perform element wise addition, subtractions, multiplication and modulus operations  

In [196]:
a = np.array([1,2,3])

In [197]:
b = np.array([4,5,6])

In [198]:
a + b

array([5, 7, 9])

In [199]:
a - b

array([-3, -3, -3])

In [200]:
a * b

array([ 4, 10, 18])

In [201]:
a % b

array([1, 2, 3])

In [202]:
a / b

array([0.25, 0.4 , 0.5 ])